'use strict';
const $=id=>document.getElementById(id);
const catalogue=window.CLIX_CATALOG;
const packs=window.CLIX_PACKS||[];
const entries=[...(catalogue?.entries||[]),...(window.CLIX_EXTRA||[]),...packs.flatMap(p=>p.entries)];
const guides=[...(window.CLIX_GUIDES||[]),...packs.flatMap(p=>p.guides)];
const topicNames={all:'All commands',security:'Security',research:'Research',opsec:'OPSEC'};
for(const pack of packs){topicNames[pack.id]=pack.label;window.CLIX_TOPICS[pack.id]=[...new Set([...(window.CLIX_TOPICS[pack.id]||[]),...pack.prefixes])];}
let topic='all',view='commands';
function hasTopic(e,t){if(t==='all')return true;if(e.topic===t)return true;const n=String(e.name||'').toLowerCase();return (window.CLIX_TOPICS?.[t]||[]).some(p=>n===p||n.startsWith(p+' ')||n.startsWith(p+'-'));}
const labels={common:'Common',windows:'Windows',linux:'Linux',osx:'macOS',android:'Android',freebsd:'FreeBSD',netbsd:'NetBSD',openbsd:'OpenBSD','cisco-ios':'Cisco IOS',dos:'DOS',sunos:'SunOS'};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved=new Set();try{saved=new Set(JSON.parse(localStorage.getItem('clix-saved')||'[]'));}catch{}
let platform='all',tool='',savedOnly=false,page=1,filtered=[],current=null;
const size=12;
const indexed=entries.map(e=>({...e,haystack:[e.name,e.description,...e.examples.map(x=>x.description+' '+x.code)].join(' ').toLowerCase()}));
const fmt=n=>n.toLocaleString('en-US');
const copyIcon='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg>';
$('total').textContent=fmt(entries.length);$('examples').textContent=fmt(entries.reduce((n,e)=>n+e.examples.length,0));$('platforms').textContent=new Set(entries.map(e=>e.platform)).size;
$('updated').textContent='Catalogue downloaded: '+new Date(catalogue.updated).toLocaleDateString('en-GB')+' · English edition';
const expansionNote=document.createElement('p');
expansionNote.textContent='Linux expansion: '+fmt(entries.filter(e=>e.platform==='linux').length)+' Linux entries, plus '+fmt(entries.filter(e=>e.platform==='common').length)+' shared-tool entries. Subcommand pages reuse selected parent examples; example totals include these appearances. Supplementary APT entries are original CLIx references checked against Debian trixie manuals and identify their source individually. Linux + shared tools includes the common collection for discovery; verify compatibility before use.';
$('updated').after(expansionNote);
labels['linux-shared']='Linux + shared tools';
const platforms=['all','linux-shared',...Object.keys(labels).filter(p=>entries.some(e=>e.platform===p))];
function renderChips(){ $('chips').innerHTML=platforms.map(p=>`<button data-platform="${p}" class="${p===platform?'active':''}" aria-pressed="${p===platform}">${p==='all'?'All platforms':labels[p]}</button>`).join(''); }
const families=[['','Everything'],['apt','APT & Debian tools'],['bash','Bash'],['systemctl','systemd services'],['ip','IP networking'],['nmcli','NetworkManager'],['dpkg','dpkg'],['dnf','DNF / Fedora'],['pacman','Pacman / Arch'],['zypper','Zypper / SUSE'],['apk','APK / Alpine'],['flatpak','Flatpak'],['snap','Snap'],['git','Git'],['docker','Docker'],['kubectl','Kubernetes'],['aws','AWS'],['az','Azure'],['gcloud','Google Cloud'],['npm','npm'],['powershell','PowerShell'],['brew','Homebrew']];
function matchesTool(e){const n=e.name.toLowerCase();if(!tool)return true;if(tool==='powershell')return e.haystack.includes('powershell');if(tool==='apt')return /^(apt(?:-| |$)|aptitude(?: |$)|add-apt-repository(?: |$)|dpkg(?:-| |$))/.test(n);if(tool==='dnf')return /^dnf5?(?:-| |$)/.test(n);return n===tool||n.startsWith(tool+' ')||n.startsWith(tool+'-');}
const specialistFamilies=[['nmap','Nmap'],['tshark','TShark'],['tcpdump','tcpdump'],['openssl','OpenSSL'],['gitleaks','Gitleaks'],['syft','Syft / SBOM'],['grype','Grype'],['trivy','Trivy'],['lynis','Lynis'],['yara','YARA'],['dig','DNS / dig'],['whois','WHOIS'],['jq','jq'],['exiftool','ExifTool'],['age','age encryption'],['gpg','GnuPG'],['restic','Restic'],['pass','Password Store']];
function renderTools(){const packFamilies=packs.flatMap(p=>p.prefixes.map(n=>[n,n]));const available=[...new Map([...families,...specialistFamilies,...packFamilies].map(pair=>[pair[0],pair])).values()];const list=topic==='all'?available:[['','All topic tools'],...available.filter(([key])=>key&&entries.some(e=>hasTopic(e,topic)&&(e.name.toLowerCase()===key||e.name.toLowerCase().startsWith(key+' ')||e.name.toLowerCase().startsWith(key+'-'))))];$('tools').innerHTML=list.map(([key,name])=>`<button data-tool="${escapeHTML(key)}" class="${tool===key?'active':''}" aria-pressed="${tool===key}">${escapeHTML(name)}</button>`).join(''); }
function syncSaved(){ $('savedCount').textContent=saved.size;$('savedNav').style.color=savedOnly?'var(--acid)':'';$('savedNav').setAttribute('aria-pressed',savedOnly); }
function toggleSaved(id){ if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem('clix-saved',JSON.stringify([...saved]));}catch{toast('Saved for this session only.');}syncSaved();if(savedOnly)search();else render();if(current===id)renderDetail(id); }
function renderTopics(){ $('topics').innerHTML=Object.entries(topicNames).map(([t,label])=>`<button data-topic="${t}" class="${topic===t?'active':''}" aria-pressed="${topic===t}">${t==='all'&&view==='guides'?'All guides':label}<small>${fmt((view==='guides'?guides:entries).filter(e=>hasTopic(e,t)).length)}</small></button>`).join(''); }
function setView(next){view=next;$('commandView').hidden=view!=='commands';$('guideView').hidden=view!=='guides';$('sort').hidden=view==='guides';$('random').hidden=view==='guides';$('directoryNav').classList.toggle('navactive',view==='commands');$('guidesNav').classList.toggle('navactive',view==='guides');$('guidesNav').setAttribute('aria-pressed',view==='guides');$('search').placeholder=view==='guides'?'Search guides and tasks…':'Search commands, tools or tasks…';renderTopics();search();}
function renderGuides(){const terms=$('search').value.toLowerCase().trim().split(/\s+/).filter(Boolean);const shown=guides.filter(g=>hasTopic(g,topic)&&terms.every(t=>[g.title,g.summary,g.prerequisites,g.topic,...g.steps.flat()].join(' ').toLowerCase().includes(t)));$('guideCount').textContent=shown.length+' guides';$('guideCards').innerHTML=shown.map(g=>`<article class="guidecard"><span class="smallcap">${escapeHTML(topicNames[g.topic])} / ${g.steps.length} STEPS</span><h2>${escapeHTML(g.title)}</h2><p>${escapeHTML(g.summary)}</p><button data-guide="${g.id}">Read guide ↗</button></article>`).join('')||'<div class="empty">No guides match. Try another topic or search.</div>';}
function openGuide(id){const g=guides.find(g=>g.id===id);if(!g)return;$('guideContent').innerHTML=`<h2>${escapeHTML(g.title)}</h2><p>${escapeHTML(g.summary)}</p><h3>Prerequisites</h3><p>${escapeHTML(g.prerequisites)}</p><ol class="guide-steps">${g.steps.map(([h,p])=>`<li><strong>${escapeHTML(h)}</strong>${escapeHTML(p)}</li>`).join('')}</ol><h3>Command references</h3><div class="guide-links">${g.references.map(id=>entries.find(e=>e.id===id)).filter(Boolean).map(e=>`<button data-guide-command="${e.id}">${escapeHTML(e.name)} ↗</button>`).join('')}</div><p class="outcome">${escapeHTML(g.outcome)}</p><h3>Sources</h3><div class="guide-sources">${g.sources.map(url=>`<a href="${safeLink(url)}" target="_blank" rel="noreferrer">${escapeHTML(new URL(url).hostname+new URL(url).pathname)} ↗</a>`).join('')}</div>`;$('guideDetail').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.topic){topic=b.dataset.topic;tool='';platform='all';renderTools();renderChips();renderTopics();search();}if(b.dataset.guide)openGuide(b.dataset.guide);if(b.dataset.guideCommand){$('guideDetail').close();openDetail(b.dataset.guideCommand);}});
function search(){
 if(view==='guides'){renderGuides();return;}
 const q=$('search').value.toLowerCase().trim(),terms=q.split(/\s+/).filter(Boolean);
 filtered=indexed.filter(e=>hasTopic(e,topic)&&(platform==='all'||e.platform===platform||(platform==='linux-shared'&&['linux','common'].includes(e.platform)))&&(!savedOnly||saved.has(e.id))&&matchesTool(e)&&terms.every(t=>e.haystack.includes(t)));
 const rank=e=>e.name.toLowerCase()===q?0:e.name.toLowerCase().startsWith(q)?1:e.name.toLowerCase().includes(q)?2:3;
 const featured=['git','ls','cd','grep','find','curl','ssh','docker','python','Get-ChildItem','npm','tar'];
 filtered.sort((a,b)=>{if($('sort').value==='relevance'){if(q){const d=rank(a)-rank(b);if(d)return d;}else if(!tool){let ai=featured.indexOf(a.name),bi=featured.indexOf(b.name);ai=ai<0?999:ai;bi=bi<0?999:bi;if(ai!==bi)return ai-bi;}}return a.name.localeCompare(b.name)||a.platform.localeCompare(b.platform);});
 page=1;render();
}
function render(){
 const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages);
 $('resultCount').textContent=fmt(filtered.length)+(savedOnly?' saved entries':' entries')+(platform!=='all'?' / '+labels[platform]:' / all platforms');
 $('cards').innerHTML=filtered.slice((page-1)*size,page*size).map(e=>`<article class="card"><div class="card-top"><span class="platform">${labels[e.platform]||e.platform}</span><button class="star ${saved.has(e.id)?'on':''}" data-save="${e.id}" aria-label="${saved.has(e.id)?'Unsave':'Save'} ${escapeHTML(e.name)}" aria-pressed="${saved.has(e.id)}">${saved.has(e.id)?'★':'☆'}</button></div><div class="commandrow"><button class="command" data-open="${e.id}">${escapeHTML(e.name)}</button><button class="copy-icon" data-copy-name="${e.id}" title="Copy command name" aria-label="Copy command name: ${escapeHTML(e.name)}">${copyIcon}</button></div><p>${escapeHTML(e.description)}</p><div class="snippetrow"><div class="snippet">${escapeHTML(e.examples[0].code)}</div><button class="copy-icon" data-copy-card="${e.id}" title="Copy example" aria-label="Copy example for ${escapeHTML(e.name)}">${copyIcon}</button></div><div class="card-foot"><span>${e.examples.length} EXAMPLES</span><button data-open="${e.id}">Open reference ↗</button></div></article>`).join('')||'<div class="empty"><h3>No commands found.</h3><p>Try a shorter search or clear the filters.</p></div>';
 $('pageNum').textContent=`${page} / ${fmt(pages)}`;$('prev').disabled=page===1;$('next').disabled=page>=pages;
 for(const button of $('cards').querySelectorAll('[data-open]')){const e=entries.find(e=>e.id===button.dataset.open);if(e?.kind==='recipe'&&button.classList.contains('command')){const badge=document.createElement('span');badge.className='badge';badge.textContent='TASK';button.closest('.card').querySelector('.platform').append(badge);}}
}
function safeLink(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?escapeHTML(u.href):'#';}catch{return '#';}}
function renderDetail(id){const e=entries.find(e=>e.id===id);if(!e)return;current=id;$('detailPlatform').textContent=(labels[e.platform]||e.platform)+' / COMMAND REFERENCE';
 $('detailContent').innerHTML=`<h2>${escapeHTML(e.name)}</h2><p>${escapeHTML(e.description)}</p><div class="detailactions"><button data-save="${e.id}">${saved.has(e.id)?'★ Saved':'☆ Save command'}</button>${e.docs?`<a href="${safeLink(e.docs)}" target="_blank" rel="noreferrer">Documentation ↗</a>`:''}<a href="${safeLink(e.source)}" target="_blank" rel="noreferrer">Source ↗</a></div><p class="warning">Read before running. Replace {{placeholders}} and confirm compatibility. Examples may modify or delete data; copying does not execute them.</p>${e.examples.map((x,i)=>`<section class="example"><p>${String(i+1).padStart(2,'0')} / ${escapeHTML(x.description)}</p><div class="codebox"><code>${escapeHTML(x.code)}</code><button class="copy-icon" data-copy="${i}" title="Copy example" aria-label="Copy example ${i+1}">${copyIcon}<span>Copy</span></button></div></section>`).join('')}<p class="smallcap">${escapeHTML(e.attribution||'tldr-pages contributors · CC BY 4.0 · adapted formatting')}</p>`;
 if(e.effect){const note=document.createElement('p');note.className='warning';note.textContent='Action: '+e.effect;$('detailContent').prepend(note);}
}
function openDetail(id){renderDetail(id);if(current!==id)return;if(!$('detail').open)$('detail').showModal();history.replaceState(null,'','#command='+encodeURIComponent(id));}
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',2200);}
async function copyText(value,message='Example copied. Check placeholders before use.'){try{await navigator.clipboard.writeText(value);toast(message);}catch{const focus=document.activeElement;const area=document.createElement('textarea');area.value=value;area.style.cssText='position:fixed;opacity:0';($('detail').open?$('detail'):document.body).append(area);area.select();const ok=document.execCommand('copy');area.remove();focus?.focus();toast(ok?message:'Copy unavailable. Select the example text manually.');}}
function copy(i){const e=entries.find(e=>e.id===current);return copyText(e.examples[i].code);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.copyCard||b.dataset.copyName;if(!id)return;const entry=entries.find(e=>e.id===id);if(entry)copyText(b.dataset.copyName?entry.name:entry.examples[0].code,b.dataset.copyName?'Command name copied.':'Example copied. Check placeholders before use.');});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open)openDetail(b.dataset.open);if(b.dataset.save)toggleSaved(b.dataset.save);if(b.dataset.copy!==undefined)copy(Number(b.dataset.copy));if(b.dataset.platform){platform=b.dataset.platform;renderChips();search();}if(b.dataset.tool!==undefined){tool=b.dataset.tool;renderTools();search();}if(b.classList.contains('close'))b.closest('dialog').close();});
$('search').addEventListener('input',search);$('sort').addEventListener('change',search);
$('reset').onclick=()=>{platform='all';tool='';topic='all';savedOnly=false;$('search').value='';$('sort').value='relevance';renderChips();renderTools();renderTopics();syncSaved();search();};
$('savedNav').onclick=()=>{savedOnly=!savedOnly;topic='all';tool='';platform='all';$('search').value='';renderTools();renderChips();syncSaved();setView('commands');$('directory').scrollIntoView();};
$('directoryNav').onclick=()=>{savedOnly=false;syncSaved();setView('commands');};
$('guidesNav').onclick=()=>{savedOnly=false;$('search').value='';syncSaved();setView('guides');};
$('prev').onclick=()=>{page--;render();$('directory').scrollIntoView();};$('next').onclick=()=>{page++;render();$('directory').scrollIntoView();};
$('random').onclick=()=>{if(filtered.length)openDetail(filtered[Math.floor(Math.random()*filtered.length)].id);else toast('Clear filters to discover a command.');};
for(const id of ['aboutOpen','aboutBottom'])$(id).onclick=()=>$('about').showModal();
for(const id of ['detail','about','guideDetail'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();}});
$('detail').addEventListener('close',()=>{current=null;history.replaceState(null,'','#directory');});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus();$('directory').scrollIntoView();}});
renderChips();renderTools();renderTopics();syncSaved();search();
if(location.hash.startsWith('#command=')){try{openDetail(decodeURIComponent(location.hash.slice(9)));}catch{}}
